### ISSUE TITLE
How to get the KAFKA_ADDR and REDIS_ADDR for configuration checking?

### ISSUE THREAD

**Issue by qihandeng2** [fission/fission-kafka-sample#13]
Dear,

I am trying to re-produce this fission kafka sample.
I am confused with this step: how to get the KAFKA_ADDR and REDIS_ADDR  for configuration checking?

**Configuration Check/Change**
Some key configuration need to be checked for having proper values:
In specs/env-java.yaml check, 

KAFKA_ADDR is pointing to appropriate address of Kafka cluster created in earlier section (Current default to my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc:9092)

REDIS_ADDR is pointing to correct Redis address within cluster (Default "redis-single-master.redis")

Thank you very much in advance.

**Comment by vishal-biyani** [comment]
Hi @qihandeng2 when you install the Kafka and Redis, you will see service objects created for them. 

So the address of Kafka:

```
my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc:9092

Pod Name		.	Svc Name		.	NameSpace . ClusterDomain: Port

```

Similarly Redis:

```
redis-single-master.redis

redis_service . namespace

```

You should be able to ping those addresses from within the cluster as a verification!

**Comment by qihandeng2** [comment]
Dear Vishal,
Thank you very much for your reply.
I almost got your idea. One more question, what does ClusterDomain mean here? Does it mean service?

Thanks again.

发件人: Vishal <notifications@github.com>
答复: fission/fission-kafka-sample <reply@reply.github.com>
日期: 2020年6月3日 星期三 下午6:37
收件人: fission/fission-kafka-sample <fission-kafka-sample@noreply.github.com>
抄送: DENG Qihang <qihandeng2-c@my.cityu.edu.hk>, Mention <mention@noreply.github.com>
主题: Re: [fission/fission-kafka-sample] How to get the KAFKA_ADDR and REDIS_ADDR for configuration checking? (#13)


Hi @qihandeng2<https://github.com/qihandeng2> when you install the Kafka and Redis, you will see service objects created for them.

So the address of Kafka:

my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc:9092



Pod Name               .       Svc Name               .       NameSpace . ClusterDomain: Port



Similarly Redis:

redis-single-master.redis



redis_service . namespace



You should be able to ping those addresses from within the cluster as a verification!

**Comment by qihandeng2** [comment]
> Hi @qihandeng2 when you install the Kafka and Redis, you will see service objects created for them.
> 
> So the address of Kafka:
> 
> ```
> my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc:9092
> 
> Pod Name		.	Svc Name		.	NameSpace . ClusterDomain: Port
> ```
> 
> Similarly Redis:
> 
> ```
> redis-single-master.redis
> 
> redis_service . namespace
> ```
> 
> You should be able to ping those addresses from within the cluster as a verification!

Thank you for your help, I got it.
